/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

// NOTE: in this Astro 6 + @astrojs/cloudflare version, `Astro.locals.runtime.env`
// has been removed (it throws at runtime). Bindings/secrets are read via
// `import { env } from 'cloudflare:workers'` instead, typed as `Cloudflare.Env`
// (see worker-configuration.d.ts, generated by `wrangler types`). We augment that
// generated interface here with the secrets that aren't declared in wrangler.toml
// (they're set via `wrangler secret put`, so `wrangler types` can't see them).
declare namespace Cloudflare {
  interface Env {
    RESEND_API_KEY: string;
    ADMIN_PASSWORD_HASH: string;
    SESSION_SECRET: string;
    VAPID_PUBLIC_KEY: string;
    VAPID_PRIVATE_KEY: string;
    VAPID_SUBJECT: string;
  }
}

// Merges into the global `Env` interface generated by `wrangler types` (which only
// knows about wrangler.toml `[vars]`/bindings, not secrets set via `wrangler secret
// put`). src/lib/*.ts functions take `env: Env` — this is the same merged shape as
// `Cloudflare.Env` above, just referenced without the namespace for convenience.
interface Env {
  RESEND_API_KEY: string;
  ADMIN_PASSWORD_HASH: string;
  SESSION_SECRET: string;
  VAPID_PUBLIC_KEY: string;
  VAPID_PRIVATE_KEY: string;
  VAPID_SUBJECT: string;
}
